// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allocate.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "allocate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace IM {

namespace {

const ::google::protobuf::Descriptor* Allocate_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Allocate_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_allocate_2eproto() {
  protobuf_AddDesc_allocate_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "allocate.proto");
  GOOGLE_CHECK(file != NULL);
  Allocate_descriptor_ = file->message_type(0);
  static const int Allocate_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Allocate, port_),
  };
  Allocate_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Allocate_descriptor_,
      Allocate::default_instance_,
      Allocate_offsets_,
      -1,
      -1,
      -1,
      sizeof(Allocate),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Allocate, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Allocate, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_allocate_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Allocate_descriptor_, &Allocate::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_allocate_2eproto() {
  delete Allocate::default_instance_;
  delete Allocate_reflection_;
}

void protobuf_AddDesc_allocate_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016allocate.proto\022\002IM\"\030\n\010Allocate\022\014\n\004port"
    "\030\001 \001(\005b\006proto3", 54);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "allocate.proto", &protobuf_RegisterTypes);
  Allocate::default_instance_ = new Allocate();
  Allocate::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_allocate_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_allocate_2eproto {
  StaticDescriptorInitializer_allocate_2eproto() {
    protobuf_AddDesc_allocate_2eproto();
  }
} static_descriptor_initializer_allocate_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Allocate::kPortFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Allocate::Allocate()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:IM.Allocate)
}

void Allocate::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Allocate::Allocate(const Allocate& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:IM.Allocate)
}

void Allocate::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  port_ = 0;
}

Allocate::~Allocate() {
  // @@protoc_insertion_point(destructor:IM.Allocate)
  SharedDtor();
}

void Allocate::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Allocate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Allocate::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Allocate_descriptor_;
}

const Allocate& Allocate::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_allocate_2eproto();
  return *default_instance_;
}

Allocate* Allocate::default_instance_ = NULL;

Allocate* Allocate::New(::google::protobuf::Arena* arena) const {
  Allocate* n = new Allocate;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Allocate::Clear() {
  port_ = 0;
}

bool Allocate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:IM.Allocate)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 port = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &port_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:IM.Allocate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:IM.Allocate)
  return false;
#undef DO_
}

void Allocate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:IM.Allocate)
  // optional int32 port = 1;
  if (this->port() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->port(), output);
  }

  // @@protoc_insertion_point(serialize_end:IM.Allocate)
}

::google::protobuf::uint8* Allocate::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:IM.Allocate)
  // optional int32 port = 1;
  if (this->port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->port(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:IM.Allocate)
  return target;
}

int Allocate::ByteSize() const {
  int total_size = 0;

  // optional int32 port = 1;
  if (this->port() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->port());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Allocate::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Allocate* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Allocate>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Allocate::MergeFrom(const Allocate& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.port() != 0) {
    set_port(from.port());
  }
}

void Allocate::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Allocate::CopyFrom(const Allocate& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Allocate::IsInitialized() const {

  return true;
}

void Allocate::Swap(Allocate* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Allocate::InternalSwap(Allocate* other) {
  std::swap(port_, other->port_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Allocate::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Allocate_descriptor_;
  metadata.reflection = Allocate_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Allocate

// optional int32 port = 1;
void Allocate::clear_port() {
  port_ = 0;
}
 ::google::protobuf::int32 Allocate::port() const {
  // @@protoc_insertion_point(field_get:IM.Allocate.port)
  return port_;
}
 void Allocate::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:IM.Allocate.port)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace IM

// @@protoc_insertion_point(global_scope)
